export const eur = (n) => new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" }).format(n || 0);
export const eur0 = (n) => new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(n || 0);
export const fmtDate = (d) => new Date(d).toLocaleDateString("it-IT", { day: "2-digit", month: "short", year: "numeric" });
export const monthKey = (d) => { const x = new Date(d); return `${x.getFullYear()}-${String(x.getMonth() + 1).padStart(2, "0")}`; };
export const mkOf = (y, m) => `${y}-${String(m + 1).padStart(2, "0")}`;
export const parseMk = (mk) => ({ y: +mk.slice(0, 4), m: +mk.slice(5, 7) - 1 });
export const addMonthsMk = (mk, n) => { const { y, m } = parseMk(mk); const d = new Date(y, m + n, 1); return mkOf(d.getFullYear(), d.getMonth()); };
export const endOfMonthIso = (mk) => { const { y, m } = parseMk(mk); return `${y}-${String(m + 1).padStart(2, "0")}-${String(new Date(y, m + 1, 0).getDate()).padStart(2, "0")}`; };
export const labelMk = (mk) => { const { y, m } = parseMk(mk); const s = new Date(y, m, 1).toLocaleDateString("it-IT", { month: "long", year: "numeric" }); return s.charAt(0).toUpperCase() + s.slice(1); };
export const labelMkShort = (mk) => { const { y, m } = parseMk(mk); return new Date(y, m, 1).toLocaleDateString("it-IT", { month: "short", year: "2-digit" }); };
export const uid = () => Math.random().toString(36).slice(2, 10) + Date.now().toString(36);
export const todayISO = () => new Date().toISOString().slice(0, 10);
export const n = (v) => { const x = Number(String(v ?? "").replace(/\s/g, "").replace(",", ".")); return Number.isFinite(x) ? x : 0; };
export const s = (v) => (v == null ? "" : String(v));
export const splitGroups = (v) => (v == null ? [] : String(v).split(/[|,]/).map((g) => g.trim()).filter(Boolean));
export const getCategoryGroups = (cat) => (cat ? splitGroups(cat.gruppo) : []);
export const getCategoryGroupLabel = (cat) => { const groups = getCategoryGroups(cat); return groups.length > 1 ? groups.join(" / ") : groups[0] || "Wants"; };
export const getTxGroup = (tx, catById) => (tx?.gruppo || (tx?.categoria ? getCategoryGroups(catById?.[tx.categoria])[0] : "") || "");
export const annoCorr = String(new Date().getFullYear());
export const dayCount = (a, b) => { if (!a || !b) return 0; const d = Math.round((new Date(b + "T12:00") - new Date(a + "T12:00")) / 86400000) + 1; return d > 0 ? d : 0; };
export const tripStatus = (t) => { const o = todayISO(); return t.partenza > o ? "futuro" : t.ritorno < o ? "passato" : "corso"; };
export const daysTo = (d) => Math.ceil((new Date(d + "T00:00") - new Date(todayISO() + "T00:00")) / 86400000);